name: Build Kernel
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build with KernelSU
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/probablypablito/kernelsu_grapheneos
          branch: 14
          config: fast
          arch: arm64
          aosp-gcc: true
          ksu: true
          ksu-version: main
          android-version: 14
          aosp-clang-version: r487747c
          anykernel3: true
